package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    //springboot 查询用户的购物车里是否此商品
    Cart selectProductFromCart(@Param("userId") Integer userId,@Param("productId") Integer productId);

    //springboot 查询用户的购物车
    List<Cart> selectCartByUserId(@Param("userId") Integer userId);

    //springboot 统计用户购物车中的购物项信息是否全选
    //0 全选
    //1 未全选
    int isAllChecked(@Param("userId") Integer userId);

    //Springboot 删除欧五车中的某些商品
    int deleteByUserIdAndProductIds(@Param("userId") Integer userId,@Param("productList") List<Integer> productList);

    //Springboot 操作购物车商品是否选中
    int makeCheckedProduct(@Param("userId") Integer userId,@Param("productId") Integer productId,@Param("flag") int flag);

    //Springboot 查询购物车中已经选中的商品
    List<Cart> searchCheckedProduct(@Param("userId") Integer userId);

    //Springboot 批量删除购物车中已经被选中的商品
    int deletehCheckedProduct(List<Cart> cartList);

    List<Cart> searchCartCheckedProduct(@Param("userId") Integer userId);

    //更具用户和productId查找
    Cart searchProductBuUserAndPId(@Param("userId") Integer userId,@Param("productId") Integer productId);

}