package com.neuedu.dao;

import com.neuedu.common.ServerResponse;
import com.neuedu.pojo.Cart;
import com.neuedu.pojo.Category;
import com.neuedu.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Set;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);


    //上架
    int upperShelf(int id);

    //下架
    int downShelf(int id);

    //分页查询
    List<Product> pageSearch(@Param("start") int start);

    //springboot分页显示
    List<Product> springbootPageSearch(@Param("start") int start,@Param("size") int size);

    //springboot 产品的模糊查询，分页
    List<Product> searchProduct(@Param("productId") Integer productId,@Param("productName") String  productName,@Param("start") int start ,@Param("size") int size);

    //springboot 产品的模糊查询.查询所有的
    List<Product> searchProductAll(@Param("productId") Integer productId,@Param("productName") String  productName);

    //前台搜索商品
    List<Product> portalSearchproduct(@Param("categoryId") int categoryId,
                                      @Param("integerSet") Set<Integer> integerSet,
                                      @Param("productName") String productName,
                                      @Param("orderBy") String orderBy,
                                      @Param("start") Integer start ,
                                      @Param("size") Integer size);

    //前台搜索所有商品
    List<Product> portalSearchproductAll(@Param("categoryId") int categoryId,
                                         @Param("integerSet") Set<Integer> integerSet,
                                         @Param("productName") String productName,
                                         @Param("orderBy") String orderBy);

    //更新商品库存
   int updateStock(@Param("productId") Integer productId,@Param("stock") Integer stock);

   //查询热销品
    List<Product> selectByIsHot();
}
