package com.neuedu.dao;

import com.neuedu.common.ServerResponse;
import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);

    public int findByUserName(String username);

    public UserInfo findByUserNameAndPassword(@Param("username") String username, @Param("password") String password);

    public List<UserInfo> findByRole(int role);

    //按照邮箱查找
    public int findByEmail(String email);

    //根据用户名查询密保问题
    public String findQuestionByUaername(@Param("username") String username);

    //校验校验密保问题答案
    public int forgetPasswordCheckAnswer(@Param("username") String username, @Param("question") String question, @Param("answer") String answer);

    //修改用户密码
    public int  updatePassword(@Param("username") String username,@Param("passwordNew") String passwordNew);

    public int updateByUsername(UserInfo record);
    }